
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header" style="float: left">
        <a class="navbar-brand" href="0_Forside.ipynb" target="_self"> <h2> &uarr; Tilbake til forsiden</h2></a>
    </div>
  </div>
</nav>

# Matriser og nøstede for-løkker

#### Læringsmål:
* Nøstede for-løkker
* Bearbeiding av matriser med løkker

In [1]:
import numpy as np
import matplotlib.pyplot as plt

## Mer om matriser
Som kjent kan vi ved hjelp av numpy lage matriser, eller 2D-arrays, som lar oss representere flere verdier. Vi kan enten lage dette fra lister. På samme måte som vi kan skrive

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

kan vi skrive følgende, med lister-i-lister

In [3]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

Da får vi en $2 \times 3$ matrise. 

Vi kan også bruke funksjoner som [`zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html) og [`ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html) til å lage lage en tom matrise. På samme måte som vi kan skrive følgende for å lage en én-dimensjonal array:

In [4]:
b = np.zeros(3)
b

array([0., 0., 0.])

...kan vi angi en liste med størrelser i 2 dimensjoner:

In [5]:
B = np.zeros([2, 3])  # Matrise med 2 rader og 3 kolonner
B

array([[0., 0., 0.],
       [0., 0., 0.]])

Som vi ser er matrisen $\boldsymbol{B}$ også en $2\times3$ matrise, akkurat som $\boldsymbol{A}$, men inneholder kun verdien $0$.

## Iterering gjennom matriser

Når man arbeider med matriser, så er ofte for-løkker essensielle for å få gjort det vi vil. Når vi skal gjøre dette, så kan numpy-funksjonen [`shape`](https://numpy.org/doc/stable/reference/generated/numpy.shape.html) komme veldig godt med. Denne kan fortelle hvor mange rader og kolonner en matrise har.

Nedenfor ser vi en eksempelfunksjon som regner ut absoluttverdien til tallene i en matrise:

In [6]:
def abs_matrix(A):
    rows, cols = np.shape(A)  # Finner dimensjonene til matrisen A
    A_abs = np.zeros([rows, cols])  # Lager en ny matrise med samme dimensjoner som A

    for i in range(rows):  # For hver rad 'i'
        for j in range(cols):  # For hver kolonne 'j'
            # Skriv inn absoluttverdien til A[i,j] i den nye matrisen A_abs[i, j]
            if A[i,j] < 0:
                A_abs[i, j] = -A[i, j]
            else:
                A_abs[i, j] = A[i, j]

    return A_abs

test_matrix = np.array([[-1, -2, -3],  # Lag en 2x3 matrise
                        [4, 5, 6]])
abs_matrix(test_matrix)

array([[1., 2., 3.],
       [4., 5., 6.]])

Tankegangen bak funksjonen `abs_matrix` kan beskrives som følger:
1. Finn antall rader og kolonner i matrisen med `shape`
2. Lag en ny "tom" matrise `A_abs` med bare nuller. Målet er at denne skal fylles med de riktige tallene etter hvert
3. Lag en for-løkke som itererer gjennom gyldige rad-indekser `i`: $0 \leq i < 2$
4. Lag en ny for-løkke *inni* den første for-løkka som itererer gjennom gyldige kolonne-indekser $j$. Denne for-løkken vil gjentas for hver radi i matrisen.
5. Nøstet inni begge for-løkkene bruker vi en if-setning til å fylle inn de riktige tallene $|a_{ij}|$ i den nye matrisen `A_abs`.



## a)

Skriv ferdig funksjonen `get_diagonal` som tar inn en matrise `A`, og returnerer en ny matrise `A_diag` der det *kun* er diagonalelementene fra `A` som er med (resten av matriseelementene er lik `0`). 

For eksempel, dersom input til funksjonen er matrisen $\boldsymbol{A}$ nedenfor, så skal output være matrisen $\boldsymbol{D}$.
$$ \boldsymbol{A} = \begin{bmatrix}
    -3 & -2 & -1 \\
    1  & 2  & 3 \\
    7 & 8 & 9
\end{bmatrix}  \;\; \rightarrow \;\; \boldsymbol{D} = \begin{bmatrix}
    -3 & 0 & 0 \\
    0 & 2 & 0 \\
    0 & 0 & 9
\end{bmatrix} $$

*Hint: et matriseelement ligger langs diagonalen dersom $i = j$*

In [7]:
def get_diagonal(A):
    height, width = np.shape(A)
    A_diag = np.zeros([height, width])
    for i in range(height):
        for j in range(width):
            A_diag[i, j] = A[i, j] if i == j else 0
    return A_diag

# Her er foreslått testkode for å teste matteeksempelet over:
A = np.array([[-3, -2, -1], 
              [1,  2,  3],
              [7,  8,  9]])
get_diagonal(A)

array([[-3.,  0.,  0.],
       [ 0.,  2.,  0.],
       [ 0.,  0.,  9.]])

In [8]:
# Denne cellen brukes under retting. La stå!

## b) 

Skriv ferdig funksjonen `get_upper` som tar inn en matrise`A`, og returnerer en ny matrise `A_upper` der det *kun* er matriseelementene fra `A` som ligger ovenfor diagonalen som er med (resten av matriseelementene er lik `0`).

For eksempel, dersom input til funksjonen er matrisen $\boldsymbol{A}$ nedenfor, så skal output være matrisen $\boldsymbol{U}$.
$$ \boldsymbol{A} = \begin{bmatrix}
    -3 & -2 & -1 \\
    1  & 2  & 3 \\
    7 & 8 & 9
\end{bmatrix}  \;\; \rightarrow \;\; \boldsymbol{U} = \begin{bmatrix}
    0 & -2 & -1 \\
    0 & 0 & 3 \\
    0 & 0 & 0
\end{bmatrix} $$

Dere har fått litt starhjelp for å få til programmet. Output-matrisen `D` er allerede deklarert, og er en matrise med samme dimensjoner som `A`, men fyllt med bare tallet `0`. Det som gjenstår er å fylle inn de riktige tallene langs diagonalen.<br>
*Hint: hvilken betingelse avgjør om et element ligger ovenfor diagonalen?*

In [10]:
def get_upper(A):
    height, width = np.shape(A)
    A_upper = np.zeros([height, width])
    for i in range(height):
        for j in range(width):
            A_upper[i, j] = A[i, j] if i < j else 0
    return A_upper


# Her er foreslått testkode for å teste matteeksempelet over:
A = np.array([[-3, -2, -1],
              [1,  2,  3],
              [7,  8,  9]])
get_upper(A)

array([[ 0., -2., -1.],
       [ 0.,  0.,  3.],
       [ 0.,  0.,  0.]])

In [ ]:
# Denne cellen brukes under retting. La stå!

<br>
<nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header" style="float: left">
                <a class="navbar-brand" href="5_matriser_intro.ipynb" target="_self">&lt; Forrige side: <i>intro til matriser</i></a>
                </div>
            <div class="navbar-header" style="float: right">
                <a class="navbar-brand" href="7_regneoperasjoner_matriser.ipynb" target="_self">Neste side: <i>matriseoperasjoner med numpy</i> &gt;</a>
            </div>
        </div>
</nav>